version: '3.7'
services:

    # ========== MySQL ==========
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ${MYSQL_VOLUME_HOST}:${MYSQL_VOLUME_CONTAINER}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
          - ${MYSQL_PORT}:3306
        networks:
          - default

    # ========== Wordpress ==========
    wordpress:
        container_name: wordpress
        image: wordpress:latest
        volumes:
          - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        ports:
          - ${WORDPRESS_HTTP}:80
          - ${WORDPRESS_HTTPS}:443
        environment:
          WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
          WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
          WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
          WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        networks:
          - default

networks:
    default: