version: '3.7'
services:

    # ========== MySQL ==========
    mysql:
        container_name: mysql.ca
        build:
          context: ./mysql
          args:
            - MYSQL_VERSION=${MYSQL_VERSION}
        volumes:
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
            - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d

        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
          - ${MYSQL_PORT}:3306
        networks:
          - BACKEND

    # ========== Wordpress ==========
    wordpress:
        container_name: wordpress.ca
        build: ./wordpress
        volumes:
          - ./wordpress/public:/var/www/html
        environment:
          WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
          WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
          WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
          WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        networks:
          - BACKEND

    # ========== nginx ==========
    nginx:
        container_name: nginx.ca
        build: ./nginx
        volumes:
          - ./nginx/certs:/data/certs
          # - ./nginx:/etc/nginx/conf.d
          - ./logs/nginx:/var/log/nginx
          - ./wordpress/public:/var/www/html
        ports:
          - ${WP_HTTP}:80
          - ${WP_HTTPS}:443
        depends_on:
          - wordpress
        networks:
          - BACKEND

networks:
    BACKEND: