version: '3.7'
services:

    # ========== MySQL ==========
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: dev
        ports:
          - 3306:3306
        networks:
          - default

    # ========== Wordpress ==========
    wordpress:
        container_name: wordpress
        image: wordpress:latest
        volumes:
          - ./wp-content:/var/www/html/wp-content
          - ./wp-config.php:/var/www/html/wp-config.php
          - ./.htaccess:/var/www/html/.htaccess
        ports:
          - 80:80
          - 443:443
        networks:
          - default

networks:
    default: