version: '3.7'
services:

    # ========== MySQL ==========
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./_db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: dev
        ports:
          - '3306:3306'
        networks:
          - default

    # ========== Wordpress ==========
    wordpress:
        container_name: wordpress
        image: wordpress:latest
        volumes:
          - ${APP_CODE_PATH_HOST}:/var/www/html/wp-content
        ports:
          - '80:80'
        environment:
          WORDPRESS_DB_HOST: mysql:3306
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: dev
        networks:
          - default

networks:
    default: