version: '3.7'
services:

    # ========== MySQL ==========
    mysql:
        container_name: mysql.ca
        build:
          context: ./mysql
          args:
            - MYSQL_VERSION=${MYSQL_VERSION}
        volumes:
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
            - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d

        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
          - ${MYSQL_PORT}:3306
        networks:
          - BACKEND

    # ========== Wordpress ==========
    wordpress:
        container_name: wordpress.ca
        build: ./wordpress
        volumes:
          - ./wordpress/wp-content:/var/www/html/wp-content
          - datavolume:/var/www/html
        environment:
          WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
          WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
          WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
          WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        networks:
          - BACKEND

    # ========== nginx ==========
    nginx:
        depends_on:
          - wordpress
        container_name: nginx.ca
        build: ./nginx
        volumes:
          - datavolume:/var/www/html
          - ./nginx/certs/api.checkoutafrica.com:/data/certs/api.checkoutafrica.com
          - ./nginx/certs/localhost:/data/certs/localhost
          # - ./nginx/conf.d/${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf
          - ${DATA_PATH_HOST}/nginx/logs:/var/log/nginx
        ports:
          - ${NGINX_HTTP}:80
          - ${NGINX_HTTPS}:443
        networks:
          - BACKEND
volumes:
  datavolume: {}
networks:
    BACKEND: